export { default as DocumentList } from './DocumentList/DocumentList'
export { default as DocumentInfo } from './DocumentInfo/DocumentInfo'
export { default as DocumentFormModal } from './DocumentFormModal/DocumentFormModal'
export { default as DocumentDelete } from './DocumentDelete/DocumentDelete'
export { default as DocumentCard } from './DocumentCard'
