export { default as LoginPage } from './LoginPage/LoginPage'
export { default as UserPage } from './UserPage/UserPage'
export { default as DocumentsPage } from './DocumentsPage/DocumentsPage'
export { default as DocumentPage } from './DocumentPage/DocumentPage'
export { default as DocumentContentPage } from './DocumentContentPage/DocumentContentPage'
export { default as SearchPage } from './SearchPage/SearchPage'

export { default as AdminDocumentsPage } from './AdminDocumentsPage/AdminDocumentsPage'
export { default as AdminDocumentPage } from './AdminDocumentPage/AdminDocumentPage'
export { default as AdminDocumentContentPage } from './AdminDocumentContentPage/AdminDocumentContentPage'
export { default as AdminUsersPage } from './AdminUsersPage/AdminUsersPage'
export { default as AdminUserPage } from './AdminUserPage/AdminUserPage'
export { default as AdminRolesPage } from './AdminRolesPage/AdminRolesPage'
export { default as AdminRolePage } from './AdminRolePage/AdminRolePage'
export { default as AdminGroupsPage } from './AdminGroupsPage/AdminGroupsPage'
export { default as AdminGroupPage } from './AdminGroupPage/AdminGroupPage'
export { default as AdminDictionaryPage } from './AdminDictionaryPage/AdminDictionaryPage'
export { default as AdminDictionaryTermPage } from './AdminDictionaryTermPage/AdminDictionaryTermPage'
export { default as AdminRecordsPage } from './AdminRecordsPage/AdminRecordsPage'
export { default as AdminRecordPage } from './AdminRecordPage/AdminRecordPage'

export { default as NotFoundPage } from './NotFoundPage/NotFoundPage'
