import {
  AppstoreTwoTone,
  AppstoreOutlined,
  PlusOutlined,
  ArrowLeftOutlined,
  ArrowRightOutlined,
  DeleteOutlined,
  MenuOutlined,
  EditOutlined,
  CloseOutlined,
  SettingOutlined,
  CheckOutlined,
  UserOutlined,
  PicLeftOutlined,
  FileTextOutlined,
  ReadOutlined,
  SearchOutlined,
  IdcardOutlined,
  TeamOutlined,
  FileOutlined,
  UploadOutlined,
  FileImageTwoTone,
  QuestionCircleOutlined,
  TableOutlined,
  MinusOutlined,
  SaveOutlined,
  VideoCameraOutlined,
  LoadingOutlined,
  ShareAltOutlined
} from '@ant-design/icons'

export const ICON = {
  app: AppstoreTwoTone,
  plus: PlusOutlined,
  left: ArrowLeftOutlined,
  right: ArrowRightOutlined,
  delete: DeleteOutlined,
  menu: MenuOutlined,
  edit: EditOutlined,
  close: CloseOutlined,
  setting: SettingOutlined,
  check: CheckOutlined,
  user: UserOutlined,
  content: PicLeftOutlined,
  document: FileTextOutlined,
  dictionary: ReadOutlined,
  search: SearchOutlined,
  dashboard: AppstoreOutlined,
  role: IdcardOutlined,
  group: TeamOutlined,
  file: FileOutlined,
  upload: UploadOutlined,
  image: FileImageTwoTone,
  question: QuestionCircleOutlined,
  table: TableOutlined,
  minus: MinusOutlined,
  save: SaveOutlined,
  record: VideoCameraOutlined,
  loading: LoadingOutlined,
  graph: ShareAltOutlined
} as const
