export { default as Layout } from './Layout/Layout'
export { default as RecordInfo } from './RecordInfo/RecordInfo'
export { default as RecordList } from './RecordList/RecordList'
export { default as RecordData } from './RecordData/RecordData'
export { default as RecordResult } from './RecordResult/RecordResult'
export { default as RecordCreate } from './RecordCreate/RecordCreate'
export { default as RecordTerms } from './RecordTerms/RecordTerms'
